id: I82CDB678
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T06:10:58+00:00'
last_modified: '2022-06-10T09:10:40.925033+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG15383
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་ཁྲིད་ཆེན་བརྒྱད་ཕྱོགས་གཅིག་ཏུ་བསྒྲིགས་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    57B3:
      image_group_id: I1KG15395
      title: Volume 1 of byang chub lam gyi rim pa'i khrid chen brgyad phyogs gcig
        tu bsgrigs pa/
      total_pages: 852
      order: 1
      base_file: 57B3.txt
    7E72:
      image_group_id: I1KG15396
      title: Volume 2 of byang chub lam gyi rim pa'i khrid chen brgyad phyogs gcig
        tu bsgrigs pa/
      total_pages: 360
      order: 2
      base_file: 7E72.txt
    31DB:
      image_group_id: I1KG15397
      title: Volume 3 of byang chub lam gyi rim pa'i khrid chen brgyad phyogs gcig
        tu bsgrigs pa/
      total_pages: 464
      order: 3
      base_file: 31DB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
